[trial]
account = "QY19851.canada-central.azure"
user = "ADMIN"
password = "{{ env_var('SNOWFLAKE_PASSWORD') }}"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "EF_PROD_RL"
schema = "PUBLIC"